---
title: 'Research Highlight: a New Classification for Traumatic Brain Injury'
author: Benjamin Gravesteijn
date: '2019-12-05'
slug: research-highlight-a-new-classification-for-traumatic-brain-injury
categories:
  - Research highlights
tags:
  - Anesthesia
  - Publications
subtitle: 'Hypothesis free analyses: can we learn anything from that?'
description: ''
image: ''
---

Last couple of weeks, I haven't been the most active on this blog, unfortunately. I started my clinical rotations, and still had to finish a couple of deadlines for my PhD. Therefore, I neglected this channel. However, I still wanted to bring you a new research highlight of [my newest paper](https://www.liebertpub.com/doi/abs/10.1089/neu.2019.6764). It has been published in the journal of Neurotrauma, and is one of the results from the CENTER-TBI study.

## Classification of TBI
Traumatic brain injury (TBI), is currently classified as "Mild", "Moderate", "Severe", based on the initial level of consciousness: the Glasgow Coma Scale (GCS). However, this classification has been criticized. Geoffrey Manley, an American Neurosurgeon known for its expertise in the field of TBI described the failure of the classification as follows: "If an oncologic patient was given the diagnosis "mild" cancer, the doctor would be laughed at". Since TBI is just as heterogeneous a disease as cancer (as much flavors), cutting the entire population in three seems very unhelpful to better treat patients or manage patient flows. Instead, it can be helpful to use more than one characteristic of the population to classify this disease, making the classification multidimensional (more than one characteristic).

One of the main purpose of the CENTER-TBI study, was to develop a multidimensional classification of TBI. And the analysis which I performed was an attempt to arrive at such a classification. We have not yet reached the final goal by this study, but I do believe we made a step into the right direction.

## Hypothesis free clustering
We have tackled this problem by performing an analysis, which falls into the category of "machine learning algorithms": a hypothesis-free clustering method. Let's break that down into pieces, to understand what we have done. 

The first concept  of our analysis, is that it is hypothesis-free. A hypothesis-based analysis assumes something, based on the hypothesis. If your hypothesis is that women are taller than men, you assume that the length is dependent on gender: íf you are a male, instead of a female, you are likely taller. Our analysis does not assume anything, no relationship between variables. Hypothesis-free is often referred to as "exploratory": you can learn something from the data that you could not have thought before the analysis. After performing this analysis, however, I beg to differ: a hypothesis-free analysis is simply harder to interpret. The found relationship between characteristics, is it temporally related, or causally? We simply do not know. This is an important limitation, which I will address later on. For me, it is the reason why our analysis is not the final answer to address the classification issue, but only one step forward.

The second concept, is "clustering". This refers to the end-product of our hypothesis-free analysis: finding groups in our data. George Orwell's _Animal Farm_ famously stated that "some animals are more equal than others". Well, this analysis tries to find patients who are "more equal" than others. For all patients, we calculate some metric which has a very similar value in some clusters, which is very different than the values in other clusters. Based on this metric, we identify 4 groups or clusters (let's not venture into the discussion about the arbitrary number...), and we describe these. These groups reflect "real" clusters in the patient data, in theory.

## Results
We described the 4 identified clusters by their outcome: "mild"", "upper intermediate", "lower intermediate", and "severe". The mild and severe cluster comprised of young patients who sustained TBI by a road traffic incident. That is intersting: the outcome was worst, and best, in the youngest patients. Does that mean that young patients can better recover from a less severe TBI than older patients, and that some experience more severe TBI's? We simply do not know. Trying to interpret directions of causality in this data is dangerous, because we did not assume anything. 
What was interesting, however, that we found that the characteristics that best described these clusters were _Glasgow coma scale_ (already used in the previous classification), _major extracranial injury_ (injury outside the head, for example a fracture), and _energy of trauma_ (whether the accident was very fast, i.e. a large traffic collision, or slower, i.e. fall in the shower). Why is this interesting? Previously, it has been established that major extracranial injury and energy of trauma do not influence outcome, if you already know their Glasgow Coma Scale. However, we were not interested in outcome: this study shows that these characteristics can be used to describe different "types" of patients, instead of patients with better or worse outcome. And this, is new. 

## Future steps
I already said, that I do not think that our study is the definite answer to the question: "how to classify TBI patients?". Instead, we were more able to answer the question: "how can we better describe TBI patients?".

```{r, echo=FALSE}
blogdown::shortcode('tweet', '1199020010712260608')
```

But, we do want to classify patients better. How to do that? I think we need to proceed by using at least a hypothesis-based method. That does not mean an analysis per sé. I think that consensus-based (perhaps a Delphi study?) can be perhaps the next step forward, of course followed by a rigorous validation. Andrew Maas, one of the directors of the CENTER-TBI study, was very attracted by the idea of "building blocks": a "type" of information (imaging, biomarkers, demographics...). Somehow, we need to define relevant relevant type of building blocks (including those that we found), and combine these into one classification. But that will not be a simple task, and needs some extra thinking. Luckily, I'm not alone, and a lot of people are thinking about this problem. At least we have enough data to validate such a classification. That's a much better starting point than 40 years ago, when the GCS was invented. That should spark our enthusiasm! 

