---
title: Anaesthesia meets Vienna
author: Benjamin Gravesteijn
date: '2019-06-04'
slug: euroanesthesia-2019
categories: ["Conference"]
tags: ["Anesthesia", "Vienna"]
---

Mentally, I started preparing for this business trip in Tokyo, Japan. After making my way over to the [national art center](www.nact.jp), I was notified that one of the new exhibitions was "Vienna on her way to Modernism". Through paintings, decorations, and fasion of the fin-de-siècle Viennese art scene, the transformation of Vienna on its way to the 20th century was meticulously displayed. From "just" a European city, to the capitol of the continent, through the development of intensive instrastructure, avant-garde architecture, and of course, the flourishing culture, centered around the Viennese bourgoisie. 

Now, more than a century later, this city is the host of the largest European conference in Anesthesiology: [EuroAnesthesia 2019](http://www.euroanaesthesia2019.com/). Vienna and Europe have come a long way since the 19th century, since this is a completely print-free, technologically driven, huge (>5000 participants) conference. I can imaging that because of this futuristic meeting, participants might forget to also enjoy the classical side of Vienna. However, that sure would not happen to me...

## Vienna
My first impressions of Vienna was that it is a green, classical city. Here, tourism feasts itself upon the 18th century architecture and other typically European achievements: Horse carriages carry asian tourists through the old, high-rising shopping streets; pamphlets are distributed which inform you about all the latest operas and plays which you definitely should visit; the ferris-wheel in the Prater-park which actually has wooden sheds as cabins... Nevertheless, the city refrains from being stereotypical: unlike walking in any other European city, walking around here actually feels like walking through the muse of all those typical cities. The archetype of a "European city". 

## Poster presentation
On the most sunniest sunday morning, my presentation was at 8:30 in the morning. The conference halls were empty, only the poster presentation corner was crowded with nervous presenters. In my session, the first two presenters were not present: they must have been fast asleep... However, there was a Ukranian ALS instructor which showed a study of CPR by foot instead of by hand. Although this looks incredibly instable, she showed comparable effectiveness. The reason for doing this? If your wrists are not too well... Another presenter, a Bosnian anesthesiologist, told us about his experiences in the bloody Bosnian war. He was able to perform 52 surgeries (with general anesthesia) without íntra-operative mortality. What happens post-operatively? He couldn't tell. 

For my presentation, I was mostly afraid that I couldn't convince the audience of the validity of the model, because they would not understand the methodology. At the end, they were still a bit too unsure to ask questions about the methodology, but they were convinced: they were confirming the study's relevance, and we discussed the implications. The American moderator did say that he did not dare ask patients whether they want to pay $50,000 for an ECMO. I replied by saying that the American system for sure is not the way we want to go, but still: you cóuld still offer it, from a cost-effective point of view.

## Conference
One of the few consistencies throughout all types of conferences is probably that we mostly know what we do not yet know. Whether it's neuro-anesthesia, traumatic brain injury, intensive care medicine, this pattern seems to keep arising. And this conference was definitly no exception.

For example, the fact that we still lack a definition for hypotension, after measuring the variable for more than hundred years, is stricking. Not only do we not know what would be a good threshold, we do not even know if we should define a threshold. Patient and disease specific thresholds would be an option, but confounding bias in observational study will not help us any further: the only measurable blood pressures, are the ones that arise circumstanially. We cannot induce a specific blood pressure, and see what the outcome would be of that patient. Hypothetically, we would have to randomy induce a certain blood pressure, in a heterogeneous group of patients, to come to the right thresholds for bad outcome. And even then will it remain inconclusive if treating the hypotension is actually treating the cause, or just the symptom of the problem. I see some opportunities in bayesian conditional posterior distributions, but I cannot wrap my head around. Or an opportunity would be to compare anesthesiologists on their average, adjusted "blood-pressure aggressiveness". That way, we can exploit the heterogeneity in treatment preference. But this is certainly food for thought. 

What is definitely food for thought is that in Denmark, they transfuse patients prehospitally. Sounds all great. However, we should take into account that in the beginning of the programme they wasted 50% of their blood products, while the effect on outcome remains inconclusive. Therefore it was suggested that they re-evaluated the programme. Especially after Marc Maegele argued that it was much preferred to not bring complicated blood products to the scene, but focus on those compounds that are known effective: fibrinogen.

There was also a great talk about the recent legalization of cannabis, and the complications for the medical field. The presenter, a bright young woman called Elena Neumann, warned us that even if we will not use it in the medical field, we will still have to deal with it more in the future. Of course, she did not speak for the Netherlands... She did go on and talk about the possible future applications for cannabinoids. For sure, the vast majority of research was done in the field of chronic pain (for which the famous painting by Frida Kahlo was showed). All these human trials remained inconclusive. What did show effectiveness, was the application to treat chemotherapy induced symptoms (nausea, cachexia). The quality of life of these patients seemed to improve. Well my opinion? Of course, marihuana relieves pain, but the dopaminergic effect also relieves you of the pains of life. It makes you happy, so is it really a medical drug? But at the end, I don't know if that should matter.

One of the things that surprised me the most was the awareness of confounding bias. Previous (neuro)anesthesiological conferences were all methodologically much less sound. However in this converence, the distinction between observational and randomized trials were repeatedly made clear. And also the fact that we cannot fully adjust for biases was repeatedly made clear. This was something that was nice to hear for a change.

The thing that I was not at all satisfied with, was the talk about machine learning and prediction. First of all, a former editor-in-chief of [Anesthesia & Analgesia](https://journals.lww.com/anesthesia-analgesia/pages/default.aspx), gave us the most enthousiastic hype talk about what incredible things could be expected of machine learning (typically American). Secondly, Hans Donald	De Boer, from the university of Groningen, came up and talked to us about all the incredible machine learning models that have been developed to predict upcoming episodes of hypotension. Although I could not detect a flaw of the development and testing phase of the model, I could not help myself to walk over to the microphone to ask a question. "Since [a recent systematic review by Christodoulou et al](https://www.jclinepi.com/article/S0895-4356(18)31081-3/abstract) showed that there is no overall superiority in discrimination of machine learning algorithms, did you try to use logistic regression, and if so, what where the results?" And then, something interesting happened. First of all, Hans Donald De Boer was a bit struck by the question, and answered that in their study, machine learning had the same performance as logistic regression (favouring my case). Second, the former editor-in-chief came up and said that "He didn't know the systematic review I was talking about, but it is just not true what I just said". And then came the awkward part... I replied with "well, that is your opinion". I'm kind of ashamed of that reaction, since this passive agressive comment would not help us any further in the discussion. What I should have said is that you can cherry pick papers which show superiority of machine learning algorithms, but overall you will not find a difference in performance. Especially not if you exclude papers with bad methodology. This will be my argument for the next discussion, which I'm sure will come.

## Vienna by night
Although all the anesthesiological discussions were great, the thing that was the most fun was the social side of it all. The Brazilian anesthesiologist, Luana Guades, which I met at the Gustav Klimmt tour remained with me all weekend. She was so kind to introduce me to all her incredibly nice Brazilian colleagues. The six of us went out for drinks and food, which actually made my conference. However she did make me feel the boring one, by her party beast mode. However, I excuse her for that. 

Furthermore, I had a great time with the residents from Rotterdam. Although the Austrian barbeque lunch on saturday was way too meaty for me to handle, the urban beach feast on sunday afternoon was just perfect. We stayed at the beach tent from mid afternoon till 10 pm, drinking more than a bottle per head. The sun stayed up, and scorched almost everybody, but it was worth it. Since the talks on monday were definitely not as interesting as the days before, this should have been the last moment of the conference. But in my memories it will. 





