---
title: Writer's visit to Milan
author: Benjamin Gravesteijn
date: '2019-07-09'
slug: writer-s-visit-to-milan
categories:
  - Conference
tags:
  - Anesthesia
  - Publications
  - Milan
---

__"Retire me to my Milan, where every third thought shall be my grave."__ 
_William Shakespeare_

Visiting Milan to write a paper at the [Ospedale Maggiore Policlinico di Milano](http://www.policlinico.mi.it): sounds like the most inspiring place to write, right? I know a professor who likes to come here for a week to write books, or funding applications. But now it's my turn to be inspired by the city of fashion, the most cultivated and wealthiest city of Italy: the country of love.

# The city
It sure wasn't my first visit to Italy, but again, the city struck me: the old roads, the chaotic traffic, the ambience of the buildings, and of course the heat... Walking around in 32 degees celsius forces you to walk not faster than a turtle would. Doing so, I walked around my first night in the city and came across some familiar, but just as many unfamiliar churches. 

Finally I googled a pizza place, for I was craving some good 'ol Italian pizza. Not knowing to what kind of place I was going to, I stumbled upon a very non-traditional place: [Pomet Milano](https://www.instagram.com/pometmilano/?hl=nl). After being seated at a table with two Italian guys (one from Rome, and one from way up north in Italy), I had the most amazing pizza ever: without toppings, but cheesy on the inside, topped with truffel oil, and some vegatables and mozzarella at the side. After an initial drink, I started talking to the guys. It's funny how in Europe, we always compare countries on culture, language, fashion, food, and women (he-he...). It's as if we are still amazed by how clumped together all these totally different countries are. Anyway, I had a great night, and Bruno and Giacomo made that happen.

The other moment of experiencing the "real" Milan, was when Nino Stochetti took us for lunch on the day after his return from China. I learned that Milanese people liked their food efficient and of high quality: no nonsense. Even though they were surprised to find out I'm vegetarian, the meal that they prepared was nonetheless excellent. Efficient, but excellent. And the stories of China, and discussions about books, got me wishing for an opportunity to come back. 

# Ospedale Maggiore
Being a big construction site, the old hospital is as modern as it is classical. Even though the building I was working in was build in 2009, it still looked as if it was build decades ago. However, experience results in knowledge, since this hospital is quite prestigious: inside and outside of Italy, people know of the merits of this hospital. 

It was very productive to work here and discuss the results. I am not used to such extensive discussion and re-evaluation of my results. It was actually very rewarding: we were able to increase the value of the work with input of experience from experience of the clinic. My co-authors really were able to connect the data with the real situation in the hospital: for that, I'm grateful. 

Finally, I was inspired by the discussions of the physicians over the currently admitted patients at the department. This inspiration was welcome, because my enthousiasm for the upcoming clinical rotation phase of my studies has been  rising and falling, as you might know. I couldn't understand a word of what they were saying (except for little hints, such as "fratello", and "psychotico", or "extradurale"), but there was something in the way they discussed patients: it was both with curiosity as well as compassion and responsibility. And this inspired me the most. 

# Future
Although we worked hard to finalize the manuscript, professor Stochetti had some major comments on the analysis which need to be addressed. I was hoping to come back with a message, and finalized results. However, as it is the case with research: I have to regain my motivation and work on it a little while more. This unfortunately messes up my detailed scheduled year of writing papers. I do think it's for the best. At the end, we want to do the best possible research. If that takes a little more time, so be it. Perhaps it buys me a ticket back to Milan...