---
title: Scientific Communication Post-Covid-19
author: Benjamin Gravesteijn
date: '2020-11-17'
slug: []
categories:
  - Thoughts
tags:
  - Life lessons
  - Rewarding
  - Covid-19
subtitle: ''
description: ''
image: ''
---

You couldn’t have missed it. The last couple of weeks were full of hopeful Covid-19 news: Pfizer and BioNTech [announced that their vaccine was 90% effective]( https://www.pfizer.com/news/press-release/press-release-detail/pfizer-and-biontech-announce-vaccine-candidate-against), followed by Moderna’s [press release that their vaccine was 94.5% effective]( https://investors.modernatx.com/news-releases/news-release-details/modernas-covid-19-vaccine-candidate-meets-its-primary-efficacy). This news was received with great anticipation and euphoria. As a result, the world stock market exploded. Nevertheless personally, I was actually quite shocked about how these companies communicated this news with the public. Both companies released not only just a point estimate, without uncertainty, it was also just a result from an interim analysis.

These interim analyses are meant to enable researchers to stop a trial, if the investigated treatment suddenly appears more harmful than standard care. These analysis are nót definitive results: the uncertainty is too large because only halve of the necessary amounts of cases have occurred. The study led by Pfizer and BioNTech have only observed 94 cases in 45000 participants, while they powered the study at 164 cases to be sufficiently sure about the effectiveness. The actual effectiveness might be much lower than this interim estimate, following the rule of  [“regression to the mean”](https://fs.blog/2015/07/regression-to-the-mean/). The actual estimate might be as lower than the 50% as advocated by the WHO. More likely, the actual estimate might decrease [towards the range of values where it is unsure that it will help us exit this pandemic.](https://www.nrc.nl/nieuws/2020/10/27/een-effectief-vaccin-bestaat-alleen-bij-geluk-zonder-weerga-a4017586)
Moreover, the fact that these results are being distributed through a press release, dismantles sciences core tradition of systematic publication. There is widespread critique on this tradition, but there is a good reason why this tradition has been with us ever since the 17th century. It is a transparent, verifiable way of evaluating the methodologies and assumptions of researchers. It is up to the reader whether they want to believe the researcher’s claim. 

By not adhering to core scientific principles, Pfizer and BioNTech have now set a precedent. Moderna had to prove itself, and throw itself into the scientific rat race by sharing preliminary results via press release. Both companies had to, out of financial, not purely scientific interests. And this act is especially sensitive in this time, where people are being led astray by confirmation bias on the internet, where the willingness to vaccinate oneself decreases per week because of doubts in the trustworthiness of the pharmaceutical industry.

It wouldn’t be halve as bad if currently developed policies are not based on these press releases; if million dollor deals aren’t being closed. I hope that a pandemic in the modern era is the ónly context where the pharmaceutical industry communicates with the public through press releases. These vaccines have the potential to end the Covid-19 crisis, please let them not mark the start the era without careful scientific communication.

